[package]
name = "backlight-popup"
description = "A popup to display xbacklight status"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.16"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
signal-hook = "0.3"
xdg = "2.4"

[profile.release]
strip = true
